# 1.Tensor的数据类型和数据类型转换

In [77]:
import torch
## 获取张量的数据类型
torch.tensor([1.2, 3.4]).dtype

torch.float64

## 1.2 改变张量的默认数据类型

In [78]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float64

In [79]:
torch.set_default_tensor_type(torch.FloatTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float32

## 1.3 改变张量的数据类型

In [80]:
a = torch.tensor([1.2, 3.4])
print(a.dtype)
print('a.long()方法：', a.long().dtype)
print('a.int()方法：', a.int().dtype)
print('a.float()方法：', a.float().dtype)

torch.float32
a.long()方法： torch.int64
a.int()方法： torch.int32
a.float()方法： torch.float32


## 1.4 获取张量默认数据类型

In [81]:
torch.get_default_dtype()

torch.float32

## 1.5 张量的生成

In [82]:
#通过torch.tensor()构造张量, dtype=...指定数据类型，requires_grad=...指定是否需要计算梯度
A = torch.tensor([[1.0, 1.0], [2,2]], dtype=torch.float32, requires_grad=True)

# 1.5.1 张量的属性

In [83]:
print('A.shape:', A.shape) #张量的形状
print('A.size():', A.size())
print('A.numel():', A.numel()) #张量的元素个数

A.shape: torch.Size([2, 2])
A.size(): torch.Size([2, 2])
A.numel(): 4


In [84]:
y = A.pow(2).sum() 
y.backward()
print(A.grad) #张量每个元素的梯度

tensor([[2., 2.],
        [4., 4.]])


### 1.5.2 ones, zeros,eyes

In [85]:
print(torch.ones(2,3))
print(torch.zeros(2,3))
print(torch.eye(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### 1.5.3**_like()

In [86]:
B = torch.arange(0,10).reshape(2,5)
print(torch.ones_like(B))
print(torch.zeros_like(B))
print(torch.rand_like(B.float()))
print(torch.diag(torch.tensor((1,2,3,4,5)))) #输出对角张量

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])
tensor([[0.4265, 0.4958, 0.8463, 0.6671, 0.4801],
        [0.6904, 0.9355, 0.6260, 0.3534, 0.6638]])
tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])


### 1.5.4 torch.new_**() 创建类型相同但是尺寸不同的张量

In [87]:
X = torch.diag(torch.tensor((1,2,3,4,5)))
print(X.new_full((3,3), fill_value=1))
print(X.new_zeros((3,3)))
print(X.new_empty((3,3)))
print(X.new_ones((3,3)))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[4692750812804284416, 4728779609836879872, 4665729215021187072],
        [4719772410577944576, 4611686019528916992, 4701758012063219712],
        [4733283209465823232, 4683743613543251968, 4724276010207412224]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


### 1.5.5 张量与Numpy数组相互转换

In [88]:
import numpy as np
F = np.ones((3,3))
#numpy数组转换为张量
Ftensor1 = torch.as_tensor(F)
Ftensor2 = torch.from_numpy(F)
#张量转换为numpy数组
a = Ftensor1.numpy()

print(Ftensor1, Ftensor2, a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 1.5.6 随机数生成张量

In [89]:
torch.manual_seed(123) #手动指定随机数种子
#分别产生服从 N(1,1^2),N(2, 2^2),N(3,3^2),N(4,4^2）的四个随机数
A_normal = torch.normal(mean=torch.arange(1,5.0), std=torch.arange(1,5.0))
print(A_normal)

tensor([0.8885, 2.2407, 1.8911, 3.0383])


In [90]:
print(torch.rand(3,4)) #服从U(0,1)的3*4张量


tensor([[0.1841, 0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164, 0.4017],
        [0.1186, 0.8274, 0.3821, 0.6605]])


In [91]:
print(torch.rand_like(A_normal)) #服从标准正态分布
print(torch.randn(3,4)) #标准正态分布

tensor([0.8536, 0.5932, 0.6367, 0.9826])
tensor([[ 0.2350,  0.6653,  0.3528,  0.9728],
        [-0.0386, -0.8861, -0.4709, -0.4269],
        [-0.0283,  1.4220, -0.3886, -0.8903]])


In [92]:
print(torch.randperm(9)) #将0-8的整数随机打乱成张量

tensor([0, 7, 5, 8, 3, 1, 6, 2, 4])


### 1.5.7 其他生成张量的函数

In [93]:
print(torch.arange(start=0, end=10, step=2)) #固定步长
print(torch.linspace(0,10,5)) #固定数量

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


## 1.6 张量的操作

In [94]:
print(torch.arange(12.0).reshape(3,4))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


### 1.6.1获取张量的元素

In [95]:
#索引和切片
A = torch.arange(12.0).reshape(1, 3, 4)
print('A:', A)
print(A[0]) #获取第0维度下所有元素
print(A[0, 0:2, :])

A: tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])


In [96]:
##  根据条件筛选
B = -A
print(torch.where(A>5,A,B)) #A中元素大于5是返回A的元素 ，否则返回B的元素
print(A[A>5]) #获取A中大于5的元素

tensor([[[-0., -1., -2., -3.],
         [-4., -5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])
tensor([ 6.,  7.,  8.,  9., 10., 11.])


In [97]:
A = torch.arange(25.0).reshape(5,5)
print(A.tril()) #获取下三角的元素，可以通过diagonal控制对角线
print(A.tril(diagonal=-1)) #获取下三角的元素，可以通过diagonal控制对角线
print(A.tril(diagonal=0)) #获取下三角的元素，可以通过diagonal控制对角线
print(A.tril(diagonal=1)) #获取下三角的元素，可以通过diagonal控制对角线
print(A.triu()) #获取上三角的元素


tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  0.,  0.,  0.],
        [10., 11., 12.,  0.,  0.],
        [15., 16., 17., 18.,  0.],
        [20., 21., 22., 23., 24.]])
tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  0.,  0.,  0.,  0.],
        [10., 11.,  0.,  0.,  0.],
        [15., 16., 17.,  0.,  0.],
        [20., 21., 22., 23.,  0.]])
tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  0.,  0.,  0.],
        [10., 11., 12.,  0.,  0.],
        [15., 16., 17., 18.,  0.],
        [20., 21., 22., 23., 24.]])
tensor([[ 0.,  1.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  0.,  0.],
        [10., 11., 12., 13.,  0.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])
tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 0.,  6.,  7.,  8.,  9.],
        [ 0.,  0., 12., 13., 14.],
        [ 0.,  0.,  0., 18., 19.],
        [ 0.,  0.,  0.,  0., 24.]])


In [98]:
#提供对角线元素生成矩阵
print(torch.diag(torch.tensor([1,2,3])))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


In [99]:
#链接张量
A = torch.arange(6.0).reshape(2,3)
B = torch.linspace(0,10,6).reshape(2,3)
print(torch.cat((A,B),dim=0), torch.cat((A,B),dim=0).shape)#维度0是列
print(torch.cat((A,B),dim=1), torch.cat((A,B),dim=1).shape)#维度1是行

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]]) torch.Size([4, 3])
tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]]) torch.Size([2, 6])


In [100]:
#stack是直接堆叠一起
F = torch.stack((A,B), dim=0)
print(F, F.shape)
F = torch.stack((A,B), dim=2)
print(F, F.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]]) torch.Size([2, 2, 3])
tensor([[[ 0.,  0.],
         [ 1.,  2.],
         [ 2.,  4.]],

        [[ 3.,  6.],
         [ 4.,  8.],
         [ 5., 10.]]]) torch.Size([2, 3, 2])


torch.split() 和 torch.chunk()可以对张量分块

### 1.6.2 张量计算

In [101]:
#比较
A = torch.randn((3,4))
B = torch.randn((3,4))
print(A>B, A<B, A==B)
print(torch.equal(A,B))#返回bool值，而不是tensor

tensor([[False,  True, False,  True],
        [False, False,  True, False],
        [ True,  True, False, False]]) tensor([[ True, False,  True, False],
        [ True,  True, False,  True],
        [False, False,  True,  True]]) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
False


In [102]:
#逐元素计算
print(A-B)
print(A/B)
print(A*B)
print(A+B)
print(A**B)
print(torch.log(A))

tensor([[-1.8118,  1.2623, -0.8829,  0.7073],
        [-1.0125, -2.0082,  0.9934, -0.3483],
        [ 0.1629,  1.6595, -1.9623, -1.5737]])
tensor([[ -0.6735,   0.0880,  -1.1891,   0.4221],
        [ -0.4428,   0.0929, -34.9510,   0.6695],
        [  1.2878,  -3.3446,  -1.2280,  -4.8070]])
tensor([[-0.7894,  0.1687, -0.1934,  0.6323],
        [-0.2181,  0.4554, -0.0267,  0.7439],
        [ 0.4127, -0.4880, -0.9526, -0.3531]])
tensor([[ 0.3535, -1.5060, -0.0763, -1.7405],
        [ 0.3910,  2.4196,  0.9381,  1.7598],
        [ 1.2951,  0.8956, -0.2008, -1.0317]])
tensor([[   nan,    nan,    nan,    nan],
        [   nan, 0.0302, 1.0010, 0.6926],
        [0.8362, 0.9107,    nan,    nan]])
tensor([[    nan,     nan,     nan,     nan],
        [    nan, -1.5813, -0.0349, -0.3485],
        [-0.3161,  0.2449,     nan,     nan]])


In [103]:
#数据裁剪
A = torch.arange(25.0).reshape(5,5)
print(torch.clamp_max(A, 12)) #最大值裁剪
print(torch.clamp_min(A, 12)) #最小值裁剪
print(torch.clamp(A, 8, 16)) #范围值裁剪

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 12., 12.],
        [12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12.]])
tensor([[12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12.],
        [12., 12., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])
tensor([[ 8.,  8.,  8.,  8.,  8.],
        [ 8.,  8.,  8.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]])


In [107]:
## 矩阵计算
print(A.T) #转置
B = torch.linspace(0, 100, 25).reshape(5,5)
print(torch.matmul(A,B)) #矩阵乘法
C = torch.arange(5.0).reshape(5,1)
print(A.matmul(C))

tensor([[ 0.,  5., 10., 15., 20.],
        [ 1.,  6., 11., 16., 21.],
        [ 2.,  7., 12., 17., 22.],
        [ 3.,  8., 13., 18., 23.],
        [ 4.,  9., 14., 19., 24.]])
tensor([[ 625.0000,  666.6667,  708.3334,  750.0000,  791.6667],
        [1666.6666, 1812.5000, 1958.3334, 2104.1667, 2250.0000],
        [2708.3333, 2958.3335, 3208.3333, 3458.3333, 3708.3335],
        [3750.0000, 4104.1670, 4458.3335, 4812.5000, 5166.6670],
        [4791.6665, 5250.0000, 5708.3335, 6166.6670, 6625.0000]])
tensor([[ 30.],
        [ 80.],
        [130.],
        [180.],
        [230.]])


In [111]:
#矩阵的逆
X = torch.rand((3,3))
Y = torch.inverse(X) #逆矩阵
print(X.matmul(Y))
print(X.trace()) #矩阵的迹

tensor([[1.0000e+00, 0.0000e+00, 1.1921e-07],
        [0.0000e+00, 1.0000e+00, 5.9605e-08],
        [1.4901e-08, 5.9605e-08, 1.0000e+00]])
tensor(2.0181)


In [123]:
#统计计算
A = torch.randn((5,5)) * 100
print(A)
print('最大值：', A.max())
print('最大值位置：', A.argmax()) #行号为 A.argmax() / 列数， 列号为A.argmax() % 列数
print('最小值：', A.min())
print('最小值位置：', A.argmin()) #行号为 A.argmax() / 列数， 列号为A.argmax() % 列数
print('每行最大值：', A.max(dim=1)) #返回最大值和最大值索引
print('每行最大值位置：', A.argmax(dim=1))


tensor([[-155.9073, -162.9471, -251.2059,  113.6582,  -73.3023],
        [ 133.8239,   27.0558,   50.7093,    3.6844,  144.6039],
        [-245.9942,   52.7654, -120.5019,  -12.8385, -190.1996],
        [ 130.4192,   40.5925,  201.2318, -232.5089, -157.7215],
        [ 134.8858,   12.2870,  132.0990,   26.7640,  -49.2329]])
最大值： tensor(201.2318)
最大值位置： tensor(17)
最小值： tensor(-251.2059)
最小值位置： tensor(2)
每行最大值： torch.return_types.max(
values=tensor([113.6582, 144.6039,  52.7654, 201.2318, 134.8858]),
indices=tensor([3, 4, 1, 2, 0]))
每行最大值位置： tensor([3, 4, 1, 2, 0])
tensor([113.6582, 144.6039,  52.7654, 201.2318, 134.8858])


In [125]:
#张量排序
print(torch.sort(A)) #升序，两个返回值
print(torch.sort(A, descending=True)) #降序

torch.return_types.sort(
values=tensor([[-251.2059, -162.9471, -155.9073,  -73.3023,  113.6582],
        [   3.6844,   27.0558,   50.7093,  133.8239,  144.6039],
        [-245.9942, -190.1996, -120.5019,  -12.8385,   52.7654],
        [-232.5089, -157.7215,   40.5925,  130.4192,  201.2318],
        [ -49.2329,   12.2870,   26.7640,  132.0990,  134.8858]]),
indices=tensor([[2, 1, 0, 4, 3],
        [3, 1, 2, 0, 4],
        [0, 4, 2, 3, 1],
        [3, 4, 1, 0, 2],
        [4, 1, 3, 2, 0]]))
torch.return_types.sort(
values=tensor([[ 113.6582,  -73.3023, -155.9073, -162.9471, -251.2059],
        [ 144.6039,  133.8239,   50.7093,   27.0558,    3.6844],
        [  52.7654,  -12.8385, -120.5019, -190.1996, -245.9942],
        [ 201.2318,  130.4192,   40.5925, -157.7215, -232.5089],
        [ 134.8858,  132.0990,   26.7640,   12.2870,  -49.2329]]),
indices=tensor([[3, 4, 0, 1, 2],
        [4, 0, 2, 1, 3],
        [1, 3, 2, 4, 0],
        [2, 0, 1, 4, 3],
        [0, 2, 3, 1, 4]]))


In [128]:
#获取张量中前K大的元素
print(A)
print(torch.topk(A,4,dim=0)) #前4大，返回两个张量，元素和索引

tensor([[-155.9073, -162.9471, -251.2059,  113.6582,  -73.3023],
        [ 133.8239,   27.0558,   50.7093,    3.6844,  144.6039],
        [-245.9942,   52.7654, -120.5019,  -12.8385, -190.1996],
        [ 130.4192,   40.5925,  201.2318, -232.5089, -157.7215],
        [ 134.8858,   12.2870,  132.0990,   26.7640,  -49.2329]])
torch.return_types.topk(
values=tensor([[ 134.8858,   52.7654,  201.2318,  113.6582,  144.6039],
        [ 133.8239,   40.5925,  132.0990,   26.7640,  -49.2329],
        [ 130.4192,   27.0558,   50.7093,    3.6844,  -73.3023],
        [-155.9073,   12.2870, -120.5019,  -12.8385, -157.7215]]),
indices=tensor([[4, 2, 3, 0, 1],
        [1, 3, 4, 4, 4],
        [3, 1, 1, 1, 0],
        [0, 4, 2, 2, 3]]))


In [130]:
# 获取第K小的元素
print(A)
print(torch.kthvalue(A, 2, dim=1))

tensor([[-155.9073, -162.9471, -251.2059,  113.6582,  -73.3023],
        [ 133.8239,   27.0558,   50.7093,    3.6844,  144.6039],
        [-245.9942,   52.7654, -120.5019,  -12.8385, -190.1996],
        [ 130.4192,   40.5925,  201.2318, -232.5089, -157.7215],
        [ 134.8858,   12.2870,  132.0990,   26.7640,  -49.2329]])
torch.return_types.kthvalue(
values=tensor([-162.9471,   27.0558, -190.1996, -157.7215,   12.2870]),
indices=tensor([1, 1, 4, 4, 1]))


In [138]:
print(torch.mean(A, dim=1))  #指定维度计算均值
print(torch.sum(A,dim=1)) #指定维度求和
print(torch.cumsum(A,dim=1)) #指定维度求累加和
print(torch.median(A,dim=1)) #指定维度求中位数，两个返回值
print(torch.cumprod(A,dim=1)) #指定维度求累乘积
print(torch.std(A,dim=0)) #计算标准差


tensor([-105.9409,   71.9755, -103.3538,   -3.5974,   51.3606])
tensor([-529.7043,  359.8773, -516.7688,  -17.9869,  256.8029])
tensor([[-155.9073, -318.8544, -570.0603, -456.4020, -529.7043],
        [ 133.8239,  160.8798,  211.5890,  215.2734,  359.8773],
        [-245.9942, -193.2289, -313.7307, -326.5692, -516.7688],
        [ 130.4192,  171.0117,  372.2435,  139.7346,  -17.9869],
        [ 134.8858,  147.1728,  279.2718,  306.0359,  256.8029]])
torch.return_types.median(
values=tensor([-155.9073,   50.7093, -120.5019,   40.5925,   26.7640]),
indices=tensor([0, 2, 2, 1, 3]))
tensor([[-1.5591e+02,  2.5405e+04, -6.3818e+06, -7.2534e+08,  5.3169e+10],
        [ 1.3382e+02,  3.6207e+03,  1.8360e+05,  6.7647e+05,  9.7821e+07],
        [-2.4599e+02, -1.2980e+04,  1.5641e+06, -2.0081e+07,  3.8194e+09],
        [ 1.3042e+02,  5.2940e+03,  1.0653e+06, -2.4770e+08,  3.9067e+10],
        [ 1.3489e+02,  1.6573e+03,  2.1893e+05,  5.8595e+06, -2.8848e+08]])
tensor([185.6952,  88.9996, 185.8161, 