# 1.Tensor的数据类型和数据类型转换

In [13]:
import torch
## 获取张量的数据类型
torch.tensor([1.2, 3.4]).dtype

torch.float16

## 1.2 改变张量的默认数据类型

In [14]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float64

In [15]:
torch.set_default_tensor_type(torch.HalfTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float16

## 1.3 改变张量的数据类型

In [16]:
a = torch.tensor([1.2, 3.4])
print(a.dtype)
print('a.long()方法：', a.long().dtype)
print('a.int()方法：', a.int().dtype)
print('a.float()方法：', a.float().dtype)

torch.float16
a.long()方法： torch.int64
a.int()方法： torch.int32
a.float()方法： torch.float32


## 1.4 获取张量默认数据类型

In [17]:
torch.get_default_dtype()

torch.float16

## 1.5 张量的生成

In [18]:
#通过torch.tensor()构造张量, dtype=...指定数据类型，requires_grad=...指定是否需要计算梯度
A = torch.tensor([[1.0, 1.0], [2,2]], dtype=torch.float32, requires_grad=True)

# 1.5.1 张量的属性

In [19]:
print('A.shape:', A.shape) #张量的形状
print('A.size():', A.size())
print('A.numel():', A.numel()) #张量的元素个数

A.shape: torch.Size([2, 2])
A.size(): torch.Size([2, 2])
A.numel(): 4


In [20]:
y = A.pow(2).sum() 
y.backward()
print(A.grad) #张量每个元素的梯度

tensor([[2., 2.],
        [4., 4.]], dtype=torch.float32)


### 1.5.2 ones, zeros,eyes

In [59]:
print(torch.ones(2,3))
print(torch.zeros(2,3))
print(torch.eye(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### 1.5.3**_like()

In [30]:
B = torch.arange(0,10).reshape(2,5)
print(torch.ones_like(B))
print(torch.zeros_like(B))
print(torch.rand_like(B.float()))
print(torch.diag(torch.tensor((1,2,3,4,5)))) #输出对角张量

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])
tensor([[0.7444, 0.2809, 0.9330, 0.1807, 0.1183],
        [0.3153, 0.4122, 0.4974, 0.1545, 0.3744]], dtype=torch.float32)
tensor([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]])


### 1.5.4 torch.new_**() 创建类型相同但是尺寸不同的张量

In [51]:
X = torch.diag(torch.tensor((1,2,3,4,5)))
print(X.new_full((3,3), fill_value=1))
print(X.new_zeros((3,3)))
print(X.new_empty((3,3)))
print(X.new_ones((3,3)))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[4605263879457472512, 4607043982877261824, 4600291434757619712],
        [4604706623020072960, 4598550106839449600, 4592566799710552064],
        [4594188390382960640, 4598165298170822656, 4592540347006976000]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


### 1.5.5 张量与Numpy数组相互转换

In [52]:
import numpy as np
F = np.ones((3,3))
#numpy数组转换为张量
Ftensor1 = torch.as_tensor(F)
Ftensor2 = torch.from_numpy(F)
#张量转换为numpy数组
a = Ftensor1.numpy()

print(Ftensor1, Ftensor2, a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 1.5.6 随机数生成张量

In [54]:
torch.manual_seed(123) #手动指定随机数种子
#分别产生服从 N(1,1^2),N(2, 2^2),N(3,3^2),N(4,4^2）的四个随机数
A_normal = torch.normal(mean=torch.arange(1,5.0), std=torch.arange(1,5.0))
print(A_normal)

tensor([0.8887, 2.2402, 1.8906, 3.0391])


In [55]:
print(torch.rand(3,4)) #服从U(0,1)的3*4张量


tensor([[0.7905, 0.0518, 0.5601, 0.7778],
        [0.6045, 0.8599, 0.0469, 0.0552],
        [0.3115, 0.0229, 0.0356, 0.7656]])


In [56]:
print(torch.rand_like(A_normal)) #服从标准正态分布
print(torch.randn(3,4)) #标准正态分布

tensor([0.4600, 0.1094, 0.0542, 0.6997])
tensor([[ 0.2350,  0.6650,  0.3528,  0.9727],
        [-0.0386, -0.8862, -0.4709, -0.4270],
        [-0.0283,  1.4219, -0.3887, -0.8901]])


In [57]:
print(torch.randperm(9)) #将0-8的整数随机打乱成张量

tensor([0, 7, 5, 8, 3, 1, 6, 2, 4])


### 1.5.7 其他生成张量的函数

In [61]:
print(torch.arange(start=0, end=10, step=2)) #固定步长
print(torch.linspace(0,10,5)) #固定数量

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


## 1.6 张量的操作

In [62]:
print(torch.arange(12.0).reshape(3,4))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
